# Generated by Axiom CLI — do not delete.
# Ensures pytest can resolve "from nodes.<module> import <func>" imports
# whether tests are run from the package root or inside the Docker build.
import sys, os as _os
sys.path.insert(0, _os.path.dirname(_os.path.dirname(_os.path.abspath(__file__))))

import numpy as np
import pytest

from gen.axiom_context import SecretStatus
from gen.messages_pb2 import PointCloud, Point3


class AxTestContext:
    """Minimal AxiomContext implementation for unit tests. Shared across all
    node test files via the `ax` fixture below."""

    class _Logger:
        def debug(self, msg: str, **attrs) -> None: pass
        def info(self, msg: str, **attrs) -> None: pass
        def warn(self, msg: str, **attrs) -> None: pass
        def error(self, msg: str, **attrs) -> None: pass

    class _Secrets:
        def __init__(self, m: dict, revoked: set) -> None:
            self._m = m or {}
            self._revoked = revoked or set()

        def get(self, name: str):
            v = self._m.get(name)
            return (v, True) if v is not None else ("", False)

        def status(self, name: str) -> SecretStatus:
            if name in self._m:
                return SecretStatus.AVAILABLE
            if name in self._revoked:
                return SecretStatus.REVOKED
            return SecretStatus.UNSET

    def __init__(self, secrets_map: dict | None = None, revoked_names: set | None = None) -> None:
        self.log = self._Logger()
        self.secrets = self._Secrets(secrets_map or {}, revoked_names)
        self.execution_id = "test-execution-id"
        self.flow_id = "test-flow-id"
        self.tenant_id = "test-tenant-id"


@pytest.fixture
def ax():
    return AxTestContext()


# --- Known-geometry fixtures -------------------------------------------------
# Synthetic clouds with hand-computable ground truth, used as independent
# oracles across the node tests (see the package retrospective).


def _cloud_msg(points: np.ndarray) -> PointCloud:
    return PointCloud(points=[Point3(x=float(p[0]), y=float(p[1]), z=float(p[2])) for p in points])


def make_transform(rx_deg=0.0, ry_deg=0.0, rz_deg=0.0, translation=(0.0, 0.0, 0.0), scale=1.0):
    """Build a row-major 4x4 homogeneous transform (16 values) — the same
    shape every node's `transform`/`initial_transform` field expects."""
    rx, ry, rz = np.radians([rx_deg, ry_deg, rz_deg])
    Rx = np.array([[1, 0, 0], [0, np.cos(rx), -np.sin(rx)], [0, np.sin(rx), np.cos(rx)]])
    Ry = np.array([[np.cos(ry), 0, np.sin(ry)], [0, 1, 0], [-np.sin(ry), 0, np.cos(ry)]])
    Rz = np.array([[np.cos(rz), -np.sin(rz), 0], [np.sin(rz), np.cos(rz), 0], [0, 0, 1]])
    R = (Rz @ Ry @ Rx) * scale
    M = np.eye(4)
    M[:3, :3] = R
    M[:3, 3] = translation
    return [float(v) for v in M.flatten(order="C")]


@pytest.fixture
def plane_grid_points():
    """A 21x21 grid of points exactly on the z=0 plane, x,y in [-1, 1].
    Oracle: plane normal (0,0,1) or (0,0,-1), d=0; centroid=(0,0,0);
    AABB = [-1,-1,0] to [1,1,0]."""
    xs = np.linspace(-1, 1, 21)
    ys = np.linspace(-1, 1, 21)
    xx, yy = np.meshgrid(xs, ys)
    pts = np.column_stack([xx.ravel(), yy.ravel(), np.zeros(xx.size)])
    return pts


@pytest.fixture
def plane_grid_cloud(plane_grid_points):
    return _cloud_msg(plane_grid_points)


@pytest.fixture
def plane_with_outliers_points(plane_grid_points):
    """The z=0 grid plus 5 far-away outlier points."""
    outliers = np.array(
        [[50.0, 50.0, 50.0], [-60.0, 10.0, 20.0], [0.0, 0.0, 100.0], [80.0, -80.0, 5.0], [-90.0, -90.0, -90.0]]
    )
    return np.vstack([plane_grid_points, outliers])


@pytest.fixture
def plane_with_outliers_cloud(plane_with_outliers_points):
    return _cloud_msg(plane_with_outliers_points)


@pytest.fixture
def unit_cube_corners():
    """The 8 corners of the axis-aligned unit cube [0,1]^3.
    Oracle: AABB min=(0,0,0) max=(1,1,1); convex hull volume=1, area=6;
    centroid=(0.5,0.5,0.5)."""
    pts = np.array(
        [[x, y, z] for x in (0.0, 1.0) for y in (0.0, 1.0) for z in (0.0, 1.0)]
    )
    return pts


@pytest.fixture
def unit_cube_cloud(unit_cube_corners):
    return _cloud_msg(unit_cube_corners)


@pytest.fixture
def two_cluster_points():
    """Two well-separated dense blobs (deterministic grid, not random) --
    oracle: DBSCAN with a modest eps should find exactly 2 clusters and 0
    noise points."""
    xs = np.linspace(0, 1, 6)
    blob_a = np.array([[x, y, 0.0] for x in xs for y in xs])
    blob_b = blob_a + np.array([100.0, 100.0, 0.0])
    return np.vstack([blob_a, blob_b])


@pytest.fixture
def two_cluster_cloud(two_cluster_points):
    return _cloud_msg(two_cluster_points)


@pytest.fixture
def fibonacci_sphere_points():
    """256 points approximately uniformly distributed on the unit sphere
    surface (deterministic Fibonacci-sphere construction, no RNG). Oracle:
    centroid ~ (0,0,0); AABB ~ [-1,-1,-1] to [1,1,1]."""
    n = 256
    i = np.arange(n)
    phi = np.arccos(1 - 2 * (i + 0.5) / n)
    golden = np.pi * (1 + 5**0.5)
    theta = golden * i
    x = np.sin(phi) * np.cos(theta)
    y = np.sin(phi) * np.sin(theta)
    z = np.cos(phi)
    return np.column_stack([x, y, z])


@pytest.fixture
def fibonacci_sphere_cloud(fibonacci_sphere_points):
    return _cloud_msg(fibonacci_sphere_points)


@pytest.fixture
def box_1x1x4_corners():
    """The 8 corners of an axis-aligned box [0,1]x[0,1]x[0,4] -- unlike a
    cube, its per-axis variances are distinct, so PCA has non-degenerate
    eigenvalues and its OBB is guaranteed axis-aligned. Oracle: obb_extents
    ~ (1,1,4) (some order), obb_volume ~ 4.0."""
    pts = np.array(
        [[x, y, z] for x in (0.0, 1.0) for y in (0.0, 1.0) for z in (0.0, 4.0)]
    )
    return pts


@pytest.fixture
def box_1x1x4_cloud(box_1x1x4_corners):
    return _cloud_msg(box_1x1x4_corners)


@pytest.fixture
def collinear_line_points():
    """21 exactly-collinear points along the x axis. Oracle: linearity ~ 1,
    planarity ~ 0, sphericity ~ 0 for interior points."""
    xs = np.linspace(-1, 1, 21)
    return np.column_stack([xs, np.zeros_like(xs), np.zeros_like(xs)])


@pytest.fixture
def collinear_line_cloud(collinear_line_points):
    return _cloud_msg(collinear_line_points)
